### ISSUE TITLE
用了之后高度似乎有问题

### ISSUE THREAD

**Issue by bulolo** [Dafrok/vue-iscroll-view#1]
似乎用了整个滚动内容可以往下拉很长，实际内容并没有那么长

**Comment by bulolo** [comment]
![image](https://cloud.githubusercontent.com/assets/10026498/20456363/69b792dc-aeb0-11e6-97b2-7adbef9083d2.png)
加了后，多出来往下拉着么多，这是什么问题？实际没用情况并没有下面这么长

**Comment by bulolo** [comment]
汇总用时出现问题：
排查发现一旦遇到 img标签。整个滑动的高度都出现问题。

**Comment by Dafrok** [comment]
@bulolo 这个是 iscroll 本身的 feature，滚动容器内容更新后需要手动触发 refresh ，详见文档 iscroll。

**Comment by Dafrok** [comment]
@bulolo 另外注意 refresh 要在 nextTick 后进行
