### ISSUE TITLE
怎么初始化scroller-view高度？

### ISSUE THREAD

**Issue by ghost** [Dafrok/vue-iscroll-view#12]
怎么初始化scroller-view高度， 不然在数据没有height:100%时候，就不能上拉下拉加载了

**Comment by Dafrok** [comment]
数据没有height 100%是什么意思？

**Comment by ghost** [comment]
如图：这个时候我得初始化高度，而不能100%;
![image](https://cloud.githubusercontent.com/assets/17811893/26537633/b2df7872-4473-11e7-9714-cb4931b06fc2.png)

**Comment by Dafrok** [comment]
高度不应该由 css 控制么？和 iscroll 有什么关系？有点懵比。你这样描述一下问题吧：
1. 这个功能你用 iscroll 会怎么去实现
2. 这个功能你用 vue-iscroll-view 怎么实现的
3. 这两种实现中哪里出现了不同的表现

**Comment by Dafrok** [comment]
@Jaction ping
