### ISSUE TITLE
vue-iscroll具备写移动端轮播的功能吗？

### ISSUE THREAD

**Issue by ghost** [Dafrok/vue-iscroll-view#13]

**Comment by Dafrok** [comment]
建议您先了解一下 iscroll 具备什么功能

**Comment by ghost** [comment]
这儿就是轮播

![image](https://cloud.githubusercontent.com/assets/17811893/26543254/c9f15866-448f-11e7-83f5-01fedf2c5fa9.png)

![image](https://cloud.githubusercontent.com/assets/17811893/26543243/c1dbea1a-448f-11e7-867e-1b4dd213ee76.png)

**Comment by Dafrok** [comment]
这个组件就是 iscroll 的声明式 换了个马甲而已 :)

**Comment by ghost** [comment]
那就是把js语法转一下vue格式，还是可以做轮播的

**Comment by Dafrok** [comment]
姑且可以这么说吧
