### ISSUE TITLE
滑動頓挫 ＩＯＳ

### ISSUE THREAD

**Issue by c941010623** [Dafrok/vue-iscroll-view#19]
在ios上
當我手指移動一點點時
往上 點放點放 之後卷軸移動距離會變成一點點
導致看起來畫面非常頓
但是我後來使用原生 Iscroll5 發現非常順......

**Comment by Dafrok** [comment]
文档中提到这个问题了，请在 CSS 中加入一行 `touch-action: none;`。

**Comment by c941010623** [comment]
剛剛測試了一樣喔
跟原生的 iscroll5 滑動的順度差別很大
手指移動一小格一小格（點、滑下、放）速度快一些
很像被snap一樣
要瞬間滑很大力 才會恢復平順
但只要重複手指移動一小格一小格（點、滑下、放）速度快一些
就又卡了......
touch-action: none; 也有加上去

測試環境：
iphone6
iphone7
ios 11
macbook pro 15' TB

**Comment by Dafrok** [comment]
https://dafrok.github.io/vue-iscroll-view/

看一下这个页面是否有同样的问题？

**Comment by c941010623** [comment]
會喔 先點放 之後的距離就是點放的距離（頓頓頓頓）

而不是加速性的（只有點放當下是短距離 之後是長距離滑動）

我這樣的形容可能無法體會
但是跟 iscroll5 的demo比的話
您大概會了解我所說的

我的客戶包含我公司ＱＡ
都覺得這是ＬＡＧ

**Comment by Dafrok** [comment]
你所使用的 iscroll 5 的 demo 是？

**Comment by c941010623** [comment]
就官方的
http://lab.cubiq.org/iscroll5/demos/scrollbars/

**Comment by c941010623** [comment]
官方的demo您連續點放之後,
再與您的連續點放比較,
就差不多可以知道我形容的意思嘍.

點放移動，點放移動～滑

**Comment by Dafrok** [comment]
还是毫无头绪啊……这个库除了代理了下 API 以外什么事情都没干，怎么会出现差异呢

**Comment by c941010623** [comment]
您有重現我所提出的BUG嗎？

**Comment by Dafrok** [comment]
没有……确实是感受不太到

**Comment by Dafrok** [comment]
没有……确实是感受不到

**Comment by shilucus** [comment]
iscroll 更新到 v5.2.0 貌似就正常了

**Comment by Dafrok** [comment]
原来如此

**Comment by Rockergmail** [comment]
使用的iphone6 iOS12 、小米4 Android 4，会出现同样的问题。注意，楼主的意思是，稍微滚动一下，没有原生的那种顺畅感。这里的确会顿挫。

**Comment by Dafrok** [comment]
8012年了，不推荐用 iscroll 了，我回头补充一个 guide 吧

**Comment by Rockergmail** [comment]
> 8012年了，不推荐用 iscroll 了，我回头补充一个 guide 吧

@Dafrok 请教一下 iscroll 的 alternative方案是什么？
