### ISSUE TITLE
0.0.7 版本非法哈希值抛出异常

### ISSUE THREAD

**Issue by bulolo** [Dafrok/vue-iscroll-view#2]
把0.0.6换成0.0.7 发现报了如下提示错误：换回0.0.6又不报这个错误
是有什么地方不同吗.感谢！
![image](https://cloud.githubusercontent.com/assets/10026498/20709645/8a663ef2-b671-11e6-94c8-5780a38e9b06.png)

**Comment by Dafrok** [comment]
0.0.7 版本加入了哈希查询初始化的支持，没有考虑到 hash 路由的情况。感谢提出 Bug，约20分钟后修复发布新版本。

**Comment by Dafrok** [comment]
@bulolo 新版本已经发布
