### ISSUE TITLE
.scroll-view样式配置问题：底部还有未显示的内容，但无法下拉了

### ISSUE THREAD

**Issue by lianghuilin** [Dafrok/vue-iscroll-view#24]
问题，如图所示：

![qq 20170926164353](https://user-images.githubusercontent.com/31031351/30851102-3276029e-a2da-11e7-92e0-7b2a1ffebaab.png)

由于显示不全容器中的内容，通过设置了top，能显示顶部了，但设置bottom却发现没生效
```
.scroll-view {
        /* -- Attention: This line is extremely important in chrome 55+! -- */
        touch-action: none;
        /* -- Attention-- */
        position: fixed;
        top: 50px;
        bottom: 0;
        left: 0;
        right: 0;
        padding-bottom: 80px;
        overflow: hidden;
    }
```

**Comment by Dafrok** [comment]
你是不是没用过 iscroll？

**Comment by lianghuilin** [comment]
非常抱歉，的确是第一次使用……还请提点一下，该怎么配置？

**Comment by Dafrok** [comment]
去查一下 iscroll 文档里一个叫 refresh 的 API 你就懂了
传送门：https://github.com/cubiq/iscroll#mastering-the-refresh-method
