### ISSUE TITLE
在iscroll-view里加图片后图片部分滑动不上去

### ISSUE THREAD

**Issue by Milkbio** [Dafrok/vue-iscroll-view#25]
`<iscroll-view class="scroll-view" :scrollerStyle="{color: 'red'}">
    <div style="border-bottom: 1px solid red;" v-for="i in 100">{{i}}</div>
    <img src="../assets/logo.png" alt="">
  </iscroll-view>`

不加这个img的时候滑动没问题，加了img后，这个图片部分滑动不上去，是因为图片异步加载然后容器没有重新计算高度吧

**Comment by Dafrok** [comment]
请手动调用 refresh

**Comment by Milkbio** [comment]
您自己遇到过这个问题吗

**Comment by Dafrok** [comment]
https://github.com/cubiq/iscroll#mastering-the-refresh-method

**Comment by Milkbio** [comment]
你好，我在mounted方法里手动延迟1s或者其他时间refresh ，还是不行，我这个图片都是加载的本地的，都没从服务器上ajax获取，直接img src=../../assets/images/pic1.png 类似这样的图片，但还是不一定哪个图片加载不到

**Comment by Dafrok** [comment]
img.onload = iscroll.refresh

**Comment by Milkbio** [comment]
我得遍历页面中所有的img 然后都加上onload事件对吗

**Comment by Dafrok** [comment]
只要影响到高度就要 refresh，请认真看 iscroll 文档的描述，不多做讨论了。

**Comment by Milkbio** [comment]
恩，好的，再问最后一个问题，麻烦你了，就是组件中没有滚动条样式属性吗

**Comment by Dafrok** [comment]
https://github.com/cubiq/iscroll#optionsscrollbars

**Comment by Dafrok** [comment]
请认真看 iscroll 文档。

https://github.com/cubiq/iscroll#optionsscrollbars
