### ISSUE TITLE
ios所有的click事件都点击不了！！

### ISSUE THREAD

**Issue by loanniss** [Dafrok/vue-iscroll-view#27]
ios所有的click事件都点击不了！！

**Comment by Dafrok** [comment]
iOS 几？

**Comment by Dafrok** [comment]
我猜是 iOS 11，因为它把移动端和 PC 端的事件拆分了，移动端是不响应 click 事件的，你可以用 touch 事件或者自己封装一个 tap 事件代替之。这里 iscroll 实现的不完善，可以去 iscroll 的仓库那边发 issue。
看你半天没反应，就先关了。如果不是 iOS 11 可以重新打开讨论。

**Comment by gaofei019** [comment]
配置option的click需要判断系统，ios中click参数为false

function iScrollClick(){
if (/iPhone|iPad|iPod|Macintosh/i.test(navigator.userAgent)) return false;
if (/Chrome/i.test(navigator.userAgent)) return (/Android/i.test(navigator.userAgent));
if (/Silk/i.test(navigator.userAgent)) return false;
if (/Android/i.test(navigator.userAgent)) {
var s=navigator.userAgent.substr(navigator.userAgent.indexOf('Android')+8,3);
return parseFloat(s[0]+s[3]) < 44 ? false : true
}
}
