### ISSUE TITLE
ios 点击事件失效/链接失效

### ISSUE THREAD

**Issue by gaofei019** [Dafrok/vue-iscroll-view#29]
ios 点击事件失效/链接失效

**Comment by Dafrok** [comment]
touch-action

**Comment by gaofei019** [comment]
配置option的click需要判断系统，ios中click参数为false

function iScrollClick(){
if (/iPhone|iPad|iPod|Macintosh/i.test(navigator.userAgent)) return false;
if (/Chrome/i.test(navigator.userAgent)) return (/Android/i.test(navigator.userAgent));
if (/Silk/i.test(navigator.userAgent)) return false;
if (/Android/i.test(navigator.userAgent)) {
var s=navigator.userAgent.substr(navigator.userAgent.indexOf('Android')+8,3);
return parseFloat(s[0]+s[3]) < 44 ? false : true
}
}

**Comment by Dafrok** [comment]
sorry，审题审错了
