### ISSUE TITLE
如何在iscroll-view里面嵌套一个iscroll-view？

### ISSUE THREAD

**Issue by cooper1x** [Dafrok/vue-iscroll-view#32]
这个在vue里面使用会遇到这个问题，比方说一个竖向iscroll里面套一个横向iscroll，横向无法滚动。
在普通html页面中，我可以通过修改iscroll源代码加入tagName白名单实现阻止内部iscroll的事件，但是这个vue版本的不知道怎么弄，preventDefault设置成什么都不行，请问怎么解决这个问题呢？

**Comment by Dafrok** [comment]
这个版本就是 iscroll 接口的一个代理，之前怎么弄现在还是怎么弄
