### ISSUE TITLE
谷歌模拟器移动端/真机不能滑动

### ISSUE THREAD

**Issue by luchanan** [Dafrok/vue-iscroll-view#5]
在谷歌模拟器移动端/真机浏览查看效果，在有高度的情况下，虽然创建了，但是不能滑动

**Comment by Dafrok** [comment]
https://dafrok.github.io/vue-iscroll-view/

**Comment by Dafrok** [comment]
https://github.com/cubiq/iscroll/issues/1109

**Comment by Dafrok** [comment]
https://dafrok.github.io/vue-iscroll-view/
