### ISSUE TITLE
可以执行pullup，scrollStart，但无法执行pullDown

### ISSUE THREAD

**Issue by manwuyu** [Dafrok/vue-iscroll-view#6]

**Comment by manwuyu** [comment]
我发现问题了，是因为我这边的数据加载，应该是我这边数据加载完成后再执行你的方法，在watch中，执行this.$refs.scrollView.refresh()就可以了

**Comment by Dafrok** [comment]
文档有写。搜索 `Call IScroll instance functions` 小节，调用实例方法 `refresh`。

**Comment by Dafrok** [comment]
另外 `pullUp` 和 `pullDown` 事件的处理存在一些争议，因为它不是 iscroll 的原生事件，为了兼容性目前仅做了最简单的判断和处理。`iscroll-probe` 的上下拉行为可以处理的更细腻，但需要手动实现。详细请参考 IScroll 的文档。

> http://iscrolljs.com/#custom-events

**Comment by manwuyu** [comment]
多谢提醒，已经完成
