### ISSUE TITLE
一直遇到高度refresh后也无法滚动问题。

### ISSUE THREAD

**Issue by bulolo** [Dafrok/vue-iscroll-view#7]
按照iscroll和文档，mounted中调用 this.$refs.scrollView.refresh()
但是在真机和谷歌浏览器 还是滚动不了。实在排查不出什么原因。
目前问题集中在，当不给dom指定高度，调用了refresh，但是依旧滚动不了，
只用每个dom都有高度的情况，才能滚动。能否请教下是否是我操作上错误。

**Comment by Dafrok** [comment]
nextTick

**Comment by bulolo** [comment]
this.$nextTick(function (){
        this.$refs.scrollView.refresh()
    })

还是没效果额

**Comment by bulolo** [comment]
页面并没有动态数据更新界面。是一个collectionview.￼￼
![screenshot](https://cloud.githubusercontent.com/assets/10026498/23534488/3dcdc45e-fff3-11e6-964c-25123baad837.png)
只要当中没有设置高度。整个就动不了。

**Comment by Dafrok** [comment]
我猜你的数据是异步加载的对吗

**Comment by Dafrok** [comment]
只要视图层在异步队列中触发重排导致高度变化，就必须在这个tick后执行refresh。比如你的图片的加载就是异步的，我猜是这个原因。

**Comment by Dafrok** [comment]
太久没有收到反馈，先close掉了。

**Comment by hoythan** [comment]
不要太完美
