### ISSUE TITLE
ios 滚动有兼容问题 ，向下滑动会卡住，被提bug 了

### ISSUE THREAD

**Issue by katoto** [Dafrok/vue-iscroll-view#8]

**Comment by Dafrok** [comment]
https://github.com/Dafrok/vue-iscroll-view/issues/5

**Comment by katoto** [comment]
找到原因了，滑出屏幕外，监听不到，touchend 事件，现在这个问题，我如何才能改你的源码呢

**Comment by Dafrok** [comment]
https://dafrok.github.io/vue-iscroll-view/ 如果这个页面也有你所说的问题，请提供详细的复现方法。如果不能，就检查一下自己的代码是不是哪里写的有问题。

**Comment by Dafrok** [comment]
ping
