### ISSUE TITLE
关于无法使用 @scroll的问题

### ISSUE THREAD

**Issue by gcdong** [Dafrok/vue-iscroll-view#9]
你好,我这边使用你这个插件的时候,需要用到 scroll这个事件,因为我这边要不断监听滚动的时候,首先我是在main.js里面 

import IScroll from 'iscroll/build/iscroll-probe.js'

然后我在vue的组件里面使用了
<iscroll-view class="scroll-view" @scroll="scrollTest">

然后我发现这个scrollTest方法是无法触发的,如果换成
<iscroll-view class="scroll-view" @scroll="scrollStart">

这个时候就可以触发了,还望指点,谢谢

**Comment by Dafrok** [comment]
probeType 设置了吗？

**Comment by Dafrok** [comment]
既然 scrollStart 被执行了 那么 scroll 事件一定是被分发了的。检查一下你的 viewModel 的实例方法是不是有问题。

**Comment by gcdong** [comment]
我发现了我没有设置probeType,
刚才设置了以后发现可以触发了,
是我没看清楚api,

谢谢你那么快回复我,真的是帮我很大的忙

Sent from YoMail

**Comment by Dafrok** [comment]
还真是因为 probeType，我看你说触发了以为你设置了所以把 comment 删了。
